### ISSUE TITLE
Is there a way to use existing Note types?

### ISSUE THREAD

**Issue by johan456789** [kerrickstaley/genanki#55]
those existing Note types already in anki. 

Do I need to find the model id? How do I do that?

Currently I'm manually changing note types after importing the deck.

**Comment by golmschenk** [comment]
I've found you can use an existing note type by getting the model ID from your `collection.anki2`. This is an SQLite database, so anything designed to inspect SQLite will be able to help you find the required data.

However, in my experience, all parts of the model must match exactly for this to work correctly. Notably, the HTML templates of the cards must also be the same. Otherwise, genanki will create a new note type. I would be interested to know if there's a way to use an existing note type, only specifying the model ID of the note type, and having the rest of the information be pulled automatically from the database. This would help in my case, where I want to add new notes using genanki, but I'd like to do the rest of the interactions/updates of the note type through the regular Anki interface.

**Comment by kerrickstaley** [comment]
You cannot re-use the built-in note types (aka models) in Anki because each Anki installation uses a unique model ID for the built-in note types. When you export the deck and someone else imports it, Anki will create a duplicate note type called e.g. Basic-123abc instead of re-using the built-in Basic note type. (You can verify this in Anki, without involving genanki, by trying to export your own Basic notes and having a friend try importing them; it will creste a new note type).

I plan to address this by adding a "Basic (genanki)" note type that behaves identically to the existing built-in type (and similar for all the other built-in note types). This way, although there will be a duplicate note type, at least it will be the same for all notes generated with genanki.

**Comment by kerrickstaley** [comment]
As of genanki version 0.9.0, you can use the following `Model`s to get the same behavior as the built-in note types:

- `genanki.BASIC_MODEL`
- `genanki.BASIC_AND_REVERSED_CARD_MODEL`
- `genanki.BASIC_OPTIONAL_REVERSED_CARD_MODEL`
- `genanki.BASIC_TYPE_IN_THE_ANSWER_MODEL`
- `genanki.CLOZE_MODEL`
    
Note that these models are called "Basic (genanki)" etc., because of the aforementioned issue with directly using the names "Basic" etc.

**Comment by johan456789** [comment]
Thanks! How about putting this info in README? I'm sure someone will find this useful.
